import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
  container: {
      display: 'flex',
      justifyContent: 'space-between',
      flex: 1,
      width: '100%',
      height: '100%',
    },
    switchContainer: {
      display: 'flex',
      flexDirection: 'row',
      width: 122,
      height: 44,
      borderRadius: 100,
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
    lightMode: {
      backgroundColor: '#A9DCFD',
      shadowColor: 'rgba(129, 129, 129, 0.15)',
      shadowOpacity: 1,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 0 },
      elevation: 5,
    },
    darkMode: {
      backgroundColor: '#1B6A9C',
    },
    chosenIcon: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: 68,
      height: '100%',
      borderRadius: 100,
    },
    switchHistoryBlock: {
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    standartIcon: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: 30,
      height: 30,
    },
  calculatorBlock: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    height: 507,
    paddingTop: 26,
    paddingBottom: 50,
    paddingLeft: 34,
    borderTopLeftRadius: 30, 
    borderTopRightRadius: 30,
  },
  columns: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '100%'
  },
  column: {
      display: 'flex',
      flexDirection: 'column',
      gap: 20,
  },
  btn: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: 70,
      height: 70,
      backgroundColor: '#C1E4FC',
      borderRadius: 100,
      paddingTop: 5,
      shadowColor: 'rgba(0, 0, 0, 0.05)',
      shadowOpacity: 1,
      shadowRadius: 15,
      shadowOffset: { width: 0, height: 3 },
      elevation: 5,
  },
  rightBtn: {
    display: 'flex',
    justifyContent: 'space-between',
    width: 70,
    height: '100%',
    backgroundColor: '#C1E4FC',
    borderRadius: 100,
  },
  text: {
      fontFamily: 'Poppins_500Medium',
      fontSize: 26,
      textAlign: 'center',
  },
  equalBtn: {
      backgroundColor: '#D0F3FF',
  },
  leftBtns: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 90,
  },
  upperBtn: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    height: 70,
    backgroundColor: '#C1E4FC',
    borderRadius: 100,
    position: 'absolute',
    left: 0,
    top: 0,
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOpacity: 1,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  leftCont: {
    width: '100%',
  },
  resultBlock: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginLeft: 34,
    marginRight: 34,
  },
  equalResults: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 70,
    height: 70,
  },
  twoTexts: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 10,
  },
  screenFirstNumber: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 22,
    textAlign: 'right'
  },
  screenSecondNumber: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 40,
    textAlign: 'right'
  },
  belowBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 15,
  }
})